// Why the degenerate run's output is "给", and why that is a NaN signature.
//
// gsm8k_full_checkpoint.json holds 587 GSM8K problems generated by this engine on a Mac. In
// most of them every channel emits one character, 给, for all 100 tokens, at temperature 0.7.
// 给 is TinyLlama's token 31999: the LAST id in its 32,000-token vocabulary.
//
// This test runs the sampler exactly as it was when that artifact was made (before 4e5eee0,
// copied verbatim below) and checks what it does with a single non-finite logit among 31,999
// healthy ones. The old softmax turns one NaN or +Inf into NaN weights everywhere, and the
// answer then depends on the C++ standard library's std::discrete_distribution:
//
//   LLVM libc++ (what Apple ships, so what that run used): the LAST index, 31999 -> 给
//   GNU libstdc++ (Linux):                                  index 0
//
// So 给 is not something the model chose. It is what the original sampler produced on a Mac
// whenever the forward pass emitted a non-finite logit — which identifies those 413 problems
// as non-finite forward passes rather than as a model fixated on a character. Commit 4e5eee0
// said the failure "pinned every sampled token to id 0"; that was measured on Linux, and on
// the platform the engine ships for it is id vocab_size - 1.
//
// The assertions are about library behaviour, deliberately: if a future libc++ changes it,
// the explanation recorded in NEXT_ON_HARDWARE.md stops being true, and this says so.
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <map>
#include <numeric>
#include <random>
#include <vector>

namespace pre_4e5eee0 {
static int32_t sampleToken(
    const _Float16* logits, int vocab_size,
    float temperature, float top_p, std::mt19937& rng
) {
    std::vector<float> probs(vocab_size);
    float max_logit = -1e9f;
    
    // Temperature scaling
    float inv_temp = 1.0f / std::max(temperature, 1e-6f);
    
    for (int i = 0; i < vocab_size; i++) {
        probs[i] = (float)logits[i] * inv_temp;
        if (probs[i] > max_logit) max_logit = probs[i];
    }
    
    // Stable softmax
    float sum_exp = 0.0f;
    for (int i = 0; i < vocab_size; i++) {
        probs[i] = expf(probs[i] - max_logit);
        sum_exp += probs[i];
    }
    for (int i = 0; i < vocab_size; i++) {
        probs[i] /= sum_exp;
    }
    
    // Top-P nucleus sampling
    if (top_p < 1.0f && top_p > 0.0f) {
        // Sort by probability descending
        std::vector<int> indices(vocab_size);
        std::iota(indices.begin(), indices.end(), 0);
        std::sort(indices.begin(), indices.end(), [&](int a, int b) {
            return probs[a] > probs[b];
        });
        
        float cumsum = 0.0f;
        int cutoff = vocab_size;
        for (int i = 0; i < vocab_size; i++) {
            cumsum += probs[indices[i]];
            if (cumsum >= top_p) {
                cutoff = i + 1;
                break;
            }
        }
        
        // Zero out tokens below cutoff
        for (int i = cutoff; i < vocab_size; i++) {
            probs[indices[i]] = 0.0f;
        }
        
        // Re-normalize
        sum_exp = 0.0f;
        for (int i = 0; i < vocab_size; i++) sum_exp += probs[i];
        for (int i = 0; i < vocab_size; i++) probs[i] /= sum_exp;
    }
    
    std::discrete_distribution<int> dist(probs.begin(), probs.end());
    return dist(rng);
}
}  // namespace pre_4e5eee0

static int failures = 0;
static void check(bool ok, const char* what) {
    std::printf("%s  %s\n", ok ? "[PASS]" : "[FAIL]", what);
    if (!ok) failures++;
}

int main() {
    const int V = 32000;   // TinyLlama's vocabulary; 31999 decodes to 给
#if defined(_LIBCPP_VERSION)
    const int expected = V - 1;
    const char* library = "LLVM libc++ (Apple's)";
#else
    const int expected = 0;
    const char* library = "GNU libstdc++";
#endif
    std::printf("standard library: %s; the old sampler should pin to token %d\n", library, expected);

    std::mt19937 g(7);
    std::normal_distribution<float> n(0.f, 2.f);
    std::vector<_Float16> healthy(V);
    for (int i = 0; i < V; i++) healthy[i] = (_Float16)n(g);

    auto run = [&](const std::vector<_Float16>& logits) {
        // As run_full_gsm8k.py called it: 8 channels, 100 tokens, T = 0.7, top_p = 0.9.
        std::map<int, int> counts;
        for (int ch = 0; ch < 8; ch++) {
            std::mt19937 rng(1000u + (uint32_t)ch * 10007u);
            for (int t = 0; t < 100; t++)
                counts[pre_4e5eee0::sampleToken(logits.data(), V, 0.7f, 0.9f, rng)]++;
        }
        return counts;
    };

    const auto control = run(healthy);
    std::printf("        (healthy logits: %zu distinct tokens over 800 draws)\n", control.size());
    check(control.size() > 100, "with healthy logits the old sampler varies, so the experiment "
                                "can tell the cases apart");

    auto one_nan = healthy;  one_nan[1234] = (_Float16)NAN;
    auto one_inf = healthy;  one_inf[1234] = (_Float16)INFINITY;
    for (auto& [name, logits] : std::vector<std::pair<const char*, std::vector<_Float16>>>{
             {"one NaN among 31,999 healthy logits", one_nan},
             {"one +Inf among 31,999 healthy logits", one_inf}}) {
        const auto counts = run(logits);
        const bool pinned = counts.size() == 1 && counts.begin()->first == expected &&
                            counts.begin()->second == 800;
        std::printf("        (%s: %zu distinct, token %d x%d)\n", name, counts.size(),
                    counts.begin()->first, counts.begin()->second);
        check(pinned, name);
    }

    std::printf("\n%s\n", failures == 0 ? "ALL CHECKS PASSED" : "THERE WERE FAILURES");
    return failures == 0 ? 0 : 1;
}
